#!/usr/bin/env bash
# P29-INF-01/03/27: Generate Secrets.xcconfig from environment variables
# Usage: ./scripts/generate_xcconfig.sh
#
# Required environment variables:
#   SUPABASE_URL       - Supabase project URL
#   SUPABASE_ANON_KEY  - Supabase anonymous API key
#
# Optional environment variables:
#   SENTRY_DSN         - Sentry Data Source Name for crash reporting
#
# Exit codes:
#   0 - Success
#   1 - Missing required environment variable(s)

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$PROJECT_ROOT/Secrets.xcconfig"

# ─── Validation ───────────────────────────────────────────────────────────────

ERRORS=()

if [[ -z "${SUPABASE_URL:-}" ]]; then
    ERRORS+=("SUPABASE_URL is not set")
fi

if [[ -z "${SUPABASE_ANON_KEY:-}" ]]; then
    ERRORS+=("SUPABASE_ANON_KEY is not set")
fi

# Validate URL format for SUPABASE_URL
if [[ -n "${SUPABASE_URL:-}" ]] && ! [[ "$SUPABASE_URL" =~ ^https?:// ]]; then
    ERRORS+=("SUPABASE_URL must start with http:// or https://")
fi

# Validate SUPABASE_ANON_KEY is not a placeholder
if [[ "${SUPABASE_ANON_KEY:-}" == "your_anon_key_here" ]] || [[ "${SUPABASE_ANON_KEY:-}" == '$(SUPABASE_ANON_KEY)' ]]; then
    ERRORS+=("SUPABASE_ANON_KEY appears to be a placeholder value")
fi

if [[ ${#ERRORS[@]} -gt 0 ]]; then
    echo "❌ Secrets validation failed:" >&2
    for err in "${ERRORS[@]}"; do
        echo "   - $err" >&2
    done
    echo "" >&2
    echo "Set required environment variables before running this script." >&2
    echo "Example:" >&2
    echo "  export SUPABASE_URL=\"https://your-project.supabase.co\"" >&2
    echo "  export SUPABASE_ANON_KEY=\"eyJ...\"" >&2
    exit 1
fi

# ─── Generate ─────────────────────────────────────────────────────────────────

cat > "$OUTPUT_FILE" <<EOF
// Secrets.xcconfig
// Auto-generated by scripts/generate_xcconfig.sh — DO NOT COMMIT
// Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
SUPABASE_URL = ${SUPABASE_URL}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

# Add optional keys if present
if [[ -n "${SENTRY_DSN:-}" ]]; then
    echo "SENTRY_DSN = ${SENTRY_DSN}" >> "$OUTPUT_FILE"
fi

if [[ -n "${REVENUE_CAT_API_KEY:-}" ]]; then
    echo "REVENUE_CAT_API_KEY = ${REVENUE_CAT_API_KEY}" >> "$OUTPUT_FILE"
fi

# ─── Verify ──────────────────────────────────────────────────────────────────

echo "✅ Secrets.xcconfig generated at: $OUTPUT_FILE"
echo "   Keys configured:"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_ANON_KEY"
[[ -n "${SENTRY_DSN:-}" ]] && echo "   - SENTRY_DSN"
[[ -n "${REVENUE_CAT_API_KEY:-}" ]] && echo "   - REVENUE_CAT_API_KEY"

# Ensure file is not tracked by git (safety check)
if git -C "$PROJECT_ROOT" ls-files --error-unmatch "$OUTPUT_FILE" &>/dev/null 2>&1; then
    echo "" >&2
    echo "⚠️  WARNING: Secrets.xcconfig is tracked by git!" >&2
    echo "   Run: git rm --cached Secrets.xcconfig" >&2
    echo "   Ensure it is listed in .gitignore" >&2
fi
